# Generated by Django 4.2.3 on 2023-08-07 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tmglobal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noc_RAT_Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RelAtTec',
            fields=[
                ('rat_pk', models.BigAutoField(auto_created=True, db_comment='Código Unico do RAT', db_index=True, primary_key=True, serialize=False, verbose_name='Código do RAT')),
                ('tp_rat', models.CharField(choices=[('A', 'Avulso'), ('C', 'Contrato'), ('G', 'Garantia')], db_comment='Tipo do Relatório de Atendimento Técnico', max_length=1, verbose_name='Tipo RAT')),
                ('dt_rat', models.DateField(db_comment='Data do Relatório de Atendimento Técnico', verbose_name='Data RAT')),
                ('dt_rat_sys', models.DateField(auto_now_add=True, db_comment='Data da Inclusão do Relatório de Atendimento Técnico', verbose_name='Data de inclusão RAT')),
                ('probl_rat', models.TextField(db_comment='Descrição do Problema Apresentado', max_length=300, verbose_name='Desc. do Problema Apresentado')),
                ('desc_rat', models.TextField(db_comment='Descrição do Atendimento do RAT', max_length=300, verbose_name='Descrição do Atendimento')),
                ('conclusao_rat', models.TextField(db_comment='Descrição da Conclusão Problema do RAT', max_length=300, verbose_name='Descrição da Conclusão Problema')),
                ('desc_pecas_rat', models.TextField(db_comment='Descrição das peças utilizadas no atendimento do RAT', max_length=300, verbose_name='Descrição das Peças do RAT')),
                ('hr_ini_rat', models.TimeField(db_comment='Hora Inicial do RAT', verbose_name='Hora Inicial do RAT')),
                ('hr_fim_rat', models.TimeField(db_comment='Hora Final do RAT', verbose_name='Hora Final do RAT')),
                ('vl_atend_rat', models.DecimalField(db_comment='Valor do atendimento do RAT', decimal_places=2, max_digits=8, verbose_name='Valor do atendimento')),
                ('vl_pecas_rat', models.DecimalField(db_comment='Valor das peças do RAT', decimal_places=2, max_digits=8, verbose_name='Valor das peças')),
                ('cod_cli', models.ForeignKey(db_comment='Código Unico do cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmglobal.clientes', verbose_name='Código do Cliente')),
                ('user_rat', models.ForeignKey(db_comment='Código Unico do Técnico', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Código do Técnico')),
            ],
        ),
    ]
