# Generated by Django 4.2.3 on 2023-07-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noc_RAT_Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RelAtTec',
            fields=[
                ('rat_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('tp_rat', models.CharField(choices=[('A', 'Avulso'), ('C', 'Contrato'), ('G', 'Garantia')], db_comment='Tipo do Relatório de Atendimento Técnico', max_length=1, verbose_name='Tipo RAT')),
                ('dt_rat', models.DateField(db_comment='Data do Relatório de Atendimento Técnico', verbose_name='Data RAT')),
                ('probl_rat', models.TextField(db_comment='Descrição do Problema Apresentado', max_length=300, verbose_name='Desc. do Problema Apresentado')),
                ('desc_rat', models.TextField(db_comment='Descrição do Atendimento do RAT', max_length=300, verbose_name='Descrição do Atendimento')),
                ('conclusao_rat', models.TextField(db_comment='Descrição da Conclusão Problema do RAT', max_length=300, verbose_name='Descrição da Conclusão Problema')),
                ('desc_pecas_rat', models.TextField(db_comment='Descrição das peças utilizadas no atendimento do RAT', max_length=300, verbose_name='Descrição das Peças do RAT')),
                ('hr_ini_rat', models.TimeField(db_comment='Hora Inicial do RAT', verbose_name='Hora Inicial do RAT')),
                ('hr_fim_rat', models.TimeField(db_comment='Hora Final do RAT', verbose_name='Hora Final do RAT')),
                ('vl_atend_rat', models.DecimalField(db_comment='Valor do atendimento do RAT', decimal_places=2, max_digits=8, verbose_name='Valor do atendimento')),
                ('vl_pecas_rat', models.DecimalField(db_comment='Valor das peças do RAT', decimal_places=2, max_digits=8, verbose_name='Valor das peças')),
            ],
        ),
    ]
