# Generated by Django 4.2.3 on 2023-07-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noc_RAT_Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RelAtTec',
            fields=[
                ('rat_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('tp_rat', models.CharField(choices=[('A', 'Avulso'), ('C', 'Contrato'), ('G', 'Garantia')], db_comment='Tipo do Relatório de Atendimento Técnico', max_length=1, verbose_name='Tipo RAT')),
                ('dt_rat', models.DateField(db_comment='Data do Relatório de Atendimento Técnico', verbose_name='Data RAT')),
            ],
        ),
    ]
