# Generated by Django 4.2.3 on 2023-07-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmglobal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cod_cli', models.IntegerField(db_comment='Código do Cliente', primary_key=True, serialize=False, verbose_name='Cód.Cliente')),
                ('seq_cli', models.IntegerField(db_comment='Sequencia do Cliente caso haja mais de um CNPJ', max_length=3, verbose_name='Seq.Cliente')),
                ('tp_cli', models.CharField(choices=[('J', 'Jurídica'), ('F', 'Física')], db_comment='Tipo de Cliente (PF, PJ)', max_length=1, verbose_name='Tipo de Cliente (PF, PJ)')),
                ('nm_jur_cli', models.CharField(db_comment='Nome Jurídico do Cliente', max_length=100, verbose_name='Nome Jurídico do Cliente')),
                ('nm_com_cli', models.CharField(blank=True, db_comment='Nome da Comercial do Cliente', max_length=60, null=True, verbose_name='Nome Comercial do Cliente')),
                ('tel_cli', models.CharField(blank=True, db_comment='Telefone do Cliente', max_length=11, null=True, verbose_name='Telefone do Cliente')),
                ('cnpj_cpf_cli', models.CharField(blank=True, db_comment='CNPJ ou CPF do Cliente', max_length=20, null=True, verbose_name='CNPJ ou CPF do Cliente')),
                ('end_cli', models.CharField(blank=True, db_comment='Endereço do Cliente', max_length=40, null=True, verbose_name='Endereço do Cliente')),
                ('end_compl_cli', models.CharField(blank=True, db_comment='Complemento do Endereço do Cliente', max_length=30, null=True, verbose_name='Complemento Endereço Cliente')),
                ('end_bairro_cli', models.CharField(blank=True, db_comment='Bairro do Endereço do Cliente', max_length=25, null=True, verbose_name='Bairro do Cliente')),
                ('end_cidade_cli', models.CharField(blank=True, db_comment='Cidade do Endereço do Cliente', max_length=35, null=True, verbose_name='Cidade do Cliente')),
                ('end_cep_cli', models.CharField(blank=True, db_comment='CEP do Endereço do Cliente', max_length=8, null=True, verbose_name='CEP do Cliente')),
                ('end_uf_cli', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapa'), ('BA', 'Bahia'), ('CE', 'Ceara'), ('DF', 'Distrito federal'), ('ES', 'Espirito santo'), ('EX', 'Estrangeiro'), ('GO', 'Goias'), ('MA', 'Maranhao'), ('MG', 'Minas gerais'), ('MS', 'Mato grosso do sul'), ('MT', 'Mato grosso'), ('PA', 'Para'), ('PB', 'Paraiba'), ('PE', 'Pernambuco'), ('PI', 'Piaui'), ('PR', 'Parana'), ('RJ', 'Rio de janeiro'), ('RN', 'Rio grande do norte'), ('RO', 'Rondonia'), ('RR', 'Roraima'), ('RS', 'Rio grande do sul'), ('SC', 'Santa catarina'), ('SE', 'Sergipe'), ('SP', 'Sao paulo'), ('TO', 'Tocantins')], db_comment='Sigla e descrição do estado brasileiro - Estrangeiro: EX', max_length=2, verbose_name='Estado UF')),
            ],
            options={
                'indexes': [models.Index(fields=['cod_cli', 'seq_cli'], name='tmglobal_cl_cod_cli_ae0f28_idx')],
            },
        ),
    ]
