# Generated by Django 4.2.3 on 2023-07-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmglobal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='noccargo',
            new_name='noc_cargo',
        ),
    ]
