# Generated by Django 4.2.3 on 2023-07-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmglobal', '0002_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='seq_cli',
            field=models.IntegerField(db_comment='Sequencia do Cliente caso haja mais de um CNPJ', verbose_name='Seq.Cliente'),
        ),
    ]
