# Generated by Django 4.2.3 on 2023-07-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmglobal', '0002_rename_noccargo_users_noc_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='noc_empresa',
            field=models.CharField(default='', max_length=50),
        ),
    ]
