# Generated by Django 4.2.3 on 2023-07-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmglobal', '0002_rename_nocusers_noc_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noc_users',
            name='noc_cargo',
        ),
        migrations.AddField(
            model_name='noc_users',
            name='departmento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
