# Generated by Django 4.2.3 on 2023-07-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmglobal', '0003_users_noc_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='noc_empresa',
            field=models.CharField(choices=[('01', 'Tecmed Matriz'), ('02', 'Tecmed Filial US')], default='', max_length=50),
        ),
    ]
