# Generated by Django 4.2.3 on 2023-07-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmglobal', '0003_alter_clientes_seq_cli'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='dt_ini_relac_cli',
            field=models.DateField(blank=True, db_comment='Data do início do relacionamento com cliente', null=True, verbose_name='Início do Relacionamento'),
        ),
    ]
