# Generated by Django 4.2.3 on 2023-07-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmglobal', '0004_alter_noc_users_departmento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noc_users',
            name='departmento',
            field=models.CharField(max_length=100),
        ),
    ]
