# Generated by Django 4.2.3 on 2023-07-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmglobal', '0004_clientes_dt_ini_relac_cli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('cod_for', models.IntegerField(db_comment='Código do Fornecedor', primary_key=True, serialize=False, verbose_name='Cód.Fornecedor')),
                ('seq_for', models.IntegerField(db_comment='Sequencia do Fornecedor caso haja mais de um CNPJ', verbose_name='Seq.Fornecedor')),
                ('tp_for', models.CharField(choices=[('J', 'Jurídica'), ('F', 'Física')], db_comment='Tipo do Fornecedor (PF, PJ)', max_length=1, verbose_name='Tipo do Fornecedor (PF, PJ)')),
                ('nm_jur_for', models.CharField(db_comment='Nome Jurídico do Fornecedor', max_length=100, verbose_name='Nome Jurídico do Fornecedor')),
                ('nm_com_for', models.CharField(blank=True, db_comment='Nome da Comercial do Fornecedor', max_length=60, null=True, verbose_name='Nome Comercial do Fornecedor')),
                ('tel_for', models.CharField(blank=True, db_comment='Telefone do Fornecedor', max_length=11, null=True, verbose_name='Telefone do Fornecedor')),
                ('cnpj_cpf_for', models.CharField(blank=True, db_comment='CNPJ ou CPF do Fornecedor', max_length=20, null=True, verbose_name='CNPJ ou CPF do Fornecedor')),
                ('end_for', models.CharField(blank=True, db_comment='Endereço do Fornecedor', max_length=40, null=True, verbose_name='Endereço do Fornecedor')),
                ('end_compl_for', models.CharField(blank=True, db_comment='Complemento do Endereço do Fornecedor', max_length=30, null=True, verbose_name='Complemento Endereço Fornecedor')),
                ('end_bairro_for', models.CharField(blank=True, db_comment='Bairro do Endereço do Fornecedor', max_length=25, null=True, verbose_name='Bairro do Fornecedor')),
                ('end_cidade_for', models.CharField(blank=True, db_comment='Cidade do Endereço do Fornecedor', max_length=35, null=True, verbose_name='Cidade do Fornecedor')),
                ('end_cep_for', models.CharField(blank=True, db_comment='CEP do Endereço do Fornecedor', max_length=8, null=True, verbose_name='CEP do Fornecedor')),
                ('end_uf_for', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapa'), ('BA', 'Bahia'), ('CE', 'Ceara'), ('DF', 'Distrito federal'), ('ES', 'Espirito santo'), ('EX', 'Estrangeiro'), ('GO', 'Goias'), ('MA', 'Maranhao'), ('MG', 'Minas gerais'), ('MS', 'Mato grosso do sul'), ('MT', 'Mato grosso'), ('PA', 'Para'), ('PB', 'Paraiba'), ('PE', 'Pernambuco'), ('PI', 'Piaui'), ('PR', 'Parana'), ('RJ', 'Rio de janeiro'), ('RN', 'Rio grande do norte'), ('RO', 'Rondonia'), ('RR', 'Roraima'), ('RS', 'Rio grande do sul'), ('SC', 'Santa catarina'), ('SE', 'Sergipe'), ('SP', 'Sao paulo'), ('TO', 'Tocantins')], db_comment='Sigla e descrição do estado brasileiro - Estrangeiro: EX', max_length=2, verbose_name='Estado UF')),
                ('dt_ini_relac_for', models.DateField(blank=True, db_comment='Data do início do relacionamento com Fornecedor', null=True, verbose_name='Início do Relacionamento')),
            ],
            options={
                'indexes': [models.Index(fields=['cod_for', 'seq_for'], name='tmglobal_fo_cod_for_f13468_idx')],
            },
        ),
    ]
