# Generated by Django 4.2.3 on 2023-07-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmglobal', '0005_alter_noc_users_departmento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noc_users',
            name='departmento',
        ),
        migrations.AddField(
            model_name='noc_users',
            name='noc_cargo',
            field=models.CharField(choices=[('A', 'Analista'), ('D', 'Diretor')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
